name: Java CI with Gradle

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  api-test:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
      - name: Setup gradlew
        run: chmod +x gradlew
      - name: Execute API Test
        run: ./gradlew cucumber -PtestType=api
      - name: Upload API Report
        uses: actions/upload-artifact@v3
        with:
          name: api-report
          path: reports/cucumber-api-report.html

  ui-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1.7.2
      - name: Setup gradlew
        run: chmod +x gradlew
      - name: Execute UI Test
        run: ./gradlew cucumber -PtestType=web
      - name: Upload UI Report
        uses: actions/upload-artifact@v3
        with:
          name: ui-report
          path: reports/cucumber-ui-report.html
